### ISSUE TITLE
AWS billing

### ISSUE THREAD

**Issue by sofer** [chaynHQ/little-window#144]
I notice that there is an RDS instance on AWS that is incurring a small (i.e. < £10) monthly charge. It might be worth working out how we want to manage this post-delivery.

**Comment by rb50** [comment]
@sofer we ended up deploying to heroku rather than AWS so think this may be a mistake as we didn't use AWS at all in the project. I think it should have been set up as a free account anyway? Either way it should be cancelled.

**Comment by rb50** [comment]
@sofer We've cancelled it now- there should be just a very small charge for March. Sorry about this- I don't think we realised there would be a charge
