### ISSUE TITLE
Database queries to show some basic info

### ISSUE THREAD

**Issue by matthewdking** [chaynHQ/little-window#223]
Hera has asked for some queries to start getting useful data from the database

Write simple queries to find out info from database
- how many convos have been had
- how long have they been
- ~which countries are they from (check IP address)~ not currently possible IP address isn't stored
- what languages people are asking for
- ratings of little window
- messages for improvements

**Comment by matthewdking** [comment]
Number of conversations 
```sql
SELECT count(*) FROM conversation;
```
how long has each conversation been
what languages are people asking for
```sql
SELECT
```
ratings of little window
```sql
SELECT
```
messages for improvements
```sql
SELECT
```

**Comment by sophieheb** [comment]
Closing as have created analytics that serves this purpose now
